# Real pipeline - lives in your pipeline repo
trigger: none  # Don't trigger on commits to the pipeline repo itself

resources:
  pipelines:
    - pipeline: sourceCodeStub       # Alias for the stub pipeline
      source: 'bobo-okeefe.demo' # Name of the stub pipeline in ADO
      project: POC-NonProd
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # Checks out pipeline repo
  - script: echo "Running real build triggered by source code commit"